import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Client } from "./protocol/client";
import { HttpTransport } from "./transport/http";
import type { Network } from "./protocol/messages";
import { errorCopy } from "./screens/errors";
import "./style.css";

const client = new Client(new HttpTransport());
function App() {
  const [step, setStep] = useState("welcome"); const [networks, setNetworks] = useState<Network[]>([]); const [selected, setSelected] = useState<Network | null>(null); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  async function start() { setStep("connecting"); try { const info = await client.call("device.info"); const qrPubkey = new URLSearchParams(window.location.search).get("pubkey") ?? String(info.pubkey); await client.open(qrPubkey); const body = await client.call("wifi.scan", { force: false }); setNetworks(body.networks as Network[]); setStep("networks"); } catch (error) { setMessage(error instanceof Error && "code" in error ? String(error.code) : "PORTAL_UNREACHABLE"); setStep("error"); } }
  async function connect() { if (!selected) return; await client.connectWifi(selected.ssid, selected.security, password); setStep("applying"); }
  useEffect(() => { if (step !== "applying") return; const timer = setInterval(async () => { const body = await client.call("wifi.status"); const phase = String(body.phase); setMessage(`${phase.replaceAll("_", " ")} ${body.ssid ?? ""}`); if (phase === "online") { clearInterval(timer); setStep("success"); } if (phase === "failed") { clearInterval(timer); setMessage(String(body.err)); setStep("error"); } }, 500); return () => clearInterval(timer); }, [step]);
  const currentError = errorCopy[message] ?? { title: "Setup needs attention", detail: message || "Could not reach the Spark simulator.", action: "Choose another network" };
  return <main><h1>Set up your DGX Spark</h1>{step === "welcome" && <><p>Scan the chassis QR code, then connect your Spark to Wi-Fi.</p><button onClick={start}>Scan the QR code</button><p className="muted">Simulator: continue with the mock QR session.</p></>}{step === "connecting" && <p>Connecting securely to your Spark…</p>}{step === "networks" && <><h2>Choose network</h2>{networks.map(n => <button className="network" disabled={n.unsupported} key={n.ssid} onClick={() => { setSelected(n); setStep("password"); }}>{n.ssid} · {n.bars}/4 bars · {n.band}{n.unsupported ? ` — ${n.reason}` : ""}</button>)}<button onClick={start}>Refresh</button></>}{step === "password" && <><h2>{selected?.ssid}</h2><input aria-label="Wi-Fi password" autoComplete="current-password" autoCapitalize="none" autoCorrect="off" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Wi-Fi password"/><p className="muted">WPA2 passwords are 8–63 characters.</p><button onClick={connect}>Send credentials</button></>}{step === "applying" && <><h2>Connecting your Spark</h2><p>{message || "Sending credentials…"}</p></>}{step === "success" && <><h2>Spark is online</h2><p>192.168.1.44 · dgx-spark-sim.local</p><p>Next: open the Spark web UI or copy an SSH command.</p></>}{step === "error" && <><h2>{currentError.title}</h2><p>{currentError.detail}</p><button onClick={() => setStep(message === "WIFI_AUTH_FAILED" ? "password" : "networks")}>{currentError.action}</button></>}</main> }
createRoot(document.getElementById("root")!).render(<App />);
